### PR TITLE
Support python 3.8 and pipenv

### LINKED ISSUE #143: Consider replacing/forking ipify for Python 3.8
`rdegges/python-ipify` hasn't been updated for some time, making `onelogin-aws-cli` fail in Python 3.8. There are PRs open, but nothing on the maintainer to approve/merge those changes.

## Expected Behavior

Client works.
## Current Behavior

```
$ /usr/local/opt/python@3.8/bin/python3 -m onelogin_aws_cli
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/onelogin_aws_cli/__init__.py", line 13, in <module>
    import ipify
  File "/usr/local/lib/python3.8/site-packages/ipify/__init__.py", line 31, in <module>
    from .ipify import get_ip
  File "/usr/local/lib/python3.8/site-packages/ipify/ipify.py", line 14, in <module>
    from .settings import API_URI, MAX_TRIES, USER_AGENT
  File "/usr/local/lib/python3.8/site-packages/ipify/settings.py", line 9, in <module>
    from platform import mac_ver, win32_ver, linux_distribution, system
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py)
```

### PR DESCRIPTION
**Pull request by sastraxi**
## Description
Replace `ipify` with `requests` to make this project Python 3.8 compatible.

## Related Issue
Fixes #143

## Motivation and Context
`python-ipify` has been abandoned and needs to be replaced. The latest version of this dependency doesn't work with Python 3.8, so it's been replaced with a simple `requests` GET.

## How Has This Been Tested?
I've run this on Python 3.8.5 (installed via homebrew) on Mac OS Catalina 10.15.2

## Help needed
I use `pipenv` and the `>=3.5` string was causing an error there. Not sure how I should be representing multiple python versions as being supported, so could use some help there.

### CODE REVIEW

File: Pipfile [hunk 1]
```diff
@@ -9,7 +9,7 @@ verify_ssl = true
 "boto3" = "*"
 onelogin = "*"
 keyring = "*"
-ipify = "*"
+requests = "*"
 
 [requires]
-python_version = ">=3.5"
+python_version = "3.8"
```
Comment (slycoder) [inline Pipfile:15]: Does this need to change?  Looks like the changes below will work fine on older versions of python as well.

Comment (sastraxi) [reply Pipfile:15]: Yes, I think so too--let me see if I can get it working locally without that change and I'll push

**Comment by sastraxi** [comment]
@slycoder I've pushed a change. Somehow `pipenv lock` worked this time with `>=3.5`. where it balked on it before. Probably because I messed up my venv before. Anyway, ready to review again!

**Comment by slycoder** [comment]
Thank you @sastraxi , I'll merge this to master!
