### ISSUE TITLE
ImportError: cannot import name 'linux_distribution' from 'platform'

### ISSUE THREAD

**Issue by dirkvanroy** [physera/onelogin-aws-cli#146]
I get the error:
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py)
when running onelogin-aws-login -C <env>

started after updating python to 3.8

onelogin-aws-login -C prod
Traceback (most recent call last):
  File "/usr/local/bin/onelogin-aws-login", line 5, in <module>
    from onelogin_aws_cli.cli import login
  File "/usr/local/lib/python3.8/site-packages/onelogin_aws_cli/__init__.py", line 13, in <module>
    import ipify
  File "/usr/local/lib/python3.8/site-packages/ipify/__init__.py", line 31, in <module>
    from .ipify import get_ip
  File "/usr/local/lib/python3.8/site-packages/ipify/ipify.py", line 14, in <module>
    from .settings import API_URI, MAX_TRIES, USER_AGENT
  File "/usr/local/lib/python3.8/site-packages/ipify/settings.py", line 9, in <module>
    from platform import mac_ver, win32_ver, linux_distribution, system
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/platform.py)

**Comment by adamlazz** [comment]
This should be fixed in 0.1.17 with https://github.com/physera/onelogin-aws-cli/pull/145 but the build failed cc/@slycoder

**Comment by slycoder** [comment]
Ok I've gone ahead and uploaded 0.1.17 to pypi.  Can you try grabbing that and seeing if that works?

**Comment by dirkvanroy** [comment]
Yes, it works. Thanks!
